package BufferApp;


/**
* BufferApp/BufferOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Buffer.idl
* martes 17 de marzo de 2026 17H06' CET
*/

public interface BufferOperations 
{
  boolean put (String elemento);
  boolean get (org.omg.CORBA.StringHolder elemento);
  boolean read (org.omg.CORBA.StringHolder elemento);
  int getNewsLength ();
  int getMaxNews ();
  boolean fijarLimiteNoticias (int numeroMaximo);
  void shutdown ();
} // interface BufferOperations
